name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    container:
      image:  circleci/ruby:2.6.3-stretch
      env:
        RAILS_ENV: test
        TZ: "/usr/share/zoneinfo/Asia/Tokyo"
        LANG: ja_JP.UTF-8
        LC_ALL: C.UTF-8
        LANGUAGE: ja_JP.UTF-8
    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
