name: Ruby

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
    #   pull_request:
    #     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - name: install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install
    - name: create DB && run test
      run: |
        bin/rails db:setup
        bundle exec rake
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        RAILS_ENV: test
